import {
  ArrowLeftRight,
  Banknote,
  CalendarCheck,
  Car,
  ChartColumn,
  ClipboardList,
  Coins,
  FileText,
  Gift,
  HandCoins,
  Landmark,
  LayoutDashboard,
  Moon,
  MoonStar,
  Package,
  PieChart,
  PiggyBank,
  Plus,
  Receipt,
  ReceiptText,
  Scale,
  ScrollText,
  Settings,
  ShieldCheck,
  SprayCan,
  Star,
  TriangleAlert,
  Users,
  UsersRound,
  Wallet,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  ArrowLeftRight,
  Banknote,
  CalendarCheck,
  Car,
  ChartColumn,
  ClipboardList,
  Coins,
  FileText,
  Gift,
  HandCoins,
  Landmark,
  LayoutDashboard,
  Moon,
  MoonStar,
  Package,
  PieChart,
  PiggyBank,
  Plus,
  Receipt,
  ReceiptText,
  Scale,
  ScrollText,
  Settings,
  ShieldCheck,
  SprayCan,
  Star,
  TriangleAlert,
  Users,
  UsersRound,
  Wallet,
  Wrench,
};

export function NavIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? LayoutDashboard;
  return <Icon className={className} aria-hidden="true" />;
}
