'use client';

import * as React from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardBody, CardHeader, CardTitle } from '@/components/ui/card';
import { ActionForm } from '@/components/forms/action-form';
import { Field, Input } from '@/components/ui/field';
import { createUserAction } from '@/lib/server/user-admin-actions';
import type { ActionResult } from '@/lib/server/operations-actions';
import { ROLE_LABELS } from './users-table';

const selectClass =
  'border-border bg-surface text-foreground h-12 w-full rounded-[var(--radius)] border px-3 text-base';

/**
 * Adding somebody.
 *
 * The first password is generated by the server and shown ONCE, here. It is
 * never written to the audit trail and cannot be read again — if it is lost,
 * the answer is to reset it, which is itself audited.
 */
export function AddUserCard({
  assignableRoles,
  canCreate,
}: {
  assignableRoles: string[];
  canCreate: boolean;
}) {
  const [open, setOpen] = React.useState(false);
  const [password, setPassword] = React.useState<string>();

  if (!canCreate) return null;

  return (
    <Card>
      <CardHeader>
        <CardTitle>Add somebody</CardTitle>
      </CardHeader>
      <CardBody className="space-y-3">
        {password && (
          <div className="bg-success-bg text-success rounded-[var(--radius)] px-3 py-3 text-sm">
            <p className="font-semibold">Temporary password: {password}</p>
            <p className="mt-1">
              Write it down now and give it to them in person. It is not stored anywhere and
              cannot be shown again. They will be asked to change it when they sign in.
            </p>
          </div>
        )}
        <Button size="sm" onClick={() => setOpen(!open)}>
          {open ? 'Close' : 'Add somebody'}
        </Button>
        {open && (
          <ActionForm
            action={createUserAction}
            submitLabel="Create account"
            onDone={(result: ActionResult) => {
              setPassword(result.id);
              setOpen(false);
            }}
          >
            <div className="space-y-3">
              <Field label="Full name" htmlFor="new-name">
                <Input id="new-name" name="full_name" required />
              </Field>
              <Field label="Phone number" htmlFor="new-phone" hint="They sign in with this.">
                <Input id="new-phone" name="phone_number" inputMode="tel" required />
              </Field>
              <Field label="Role" htmlFor="new-role">
                <select id="new-role" name="role" required className={selectClass}>
                  <option value="">Choose…</option>
                  {assignableRoles.map((role) => (
                    <option key={role} value={role}>
                      {ROLE_LABELS[role] ?? role}
                    </option>
                  ))}
                </select>
              </Field>
              <Field label="Staff ID" htmlFor="new-staff" hint="Optional, e.g. RMX-STF-0001.">
                <Input id="new-staff" name="staff_id" />
              </Field>
              <Field label="Why" htmlFor="new-reason" hint="Optional, kept in the audit trail.">
                <Input id="new-reason" name="reason" />
              </Field>
            </div>
          </ActionForm>
        )}
      </CardBody>
    </Card>
  );
}
