// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo1QEPh5a11sTTi954cPE3dDshm6GX-b8',
    appId: '1:499633828471:web:88f7ef96aad7d431bd4c72',
    messagingSenderId: '499633828471',
    projectId: 'ramos1-c0862',
    authDomain: 'ramos1-c0862.firebaseapp.com',
    storageBucket: 'ramos1-c0862.firebasestorage.app',
    measurementId: 'G-FE90WRLNZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJv27cCTzsyoH251MPDtLqK3SDhtFnP_Y',
    appId: '1:499633828471:android:b5a9031ab77245debd4c72',
    messagingSenderId: '499633828471',
    projectId: 'ramos1-c0862',
    storageBucket: 'ramos1-c0862.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGYvhUX7M_lK371dzj5-hchGyD9r0eQk',
    appId: '1:499633828471:ios:e50f4254115f263ebd4c72',
    messagingSenderId: '499633828471',
    projectId: 'ramos1-c0862',
    storageBucket: 'ramos1-c0862.firebasestorage.app',
    iosBundleId: 'com.ramosmax.automotive.dev',
  );
}
