#!/usr/bin/env node
/**
 * Creates the FIRST RamosMAX administrator on a new project.
 *
 * There is a chicken and egg here: `app.create_user` requires `users.create`,
 * which only an administrator holds, and a new project has none. This script
 * is the one supported way through it, and it goes through the same two halves
 * every account goes through:
 *
 *   1. a CREDENTIAL, with a hidden identity nobody types — a random address on
 *      the reserved `.invalid` domain, and a generated password, both from
 *      `app.new_user_credentials()` so no human chooses either;
 *   2. a PROFILE, written by `app.bootstrap_first_admin`, which refuses the
 *      moment any administrator exists.
 *
 * The account it makes is an ordinary one: phone number and password at the
 * login form, `must_change_password` set so the first thing that happens is
 * the password being replaced, a full audit entry, and every permission an
 * Administrator holds — no more.
 *
 * The password is printed ONCE. It is not stored anywhere in readable form and
 * cannot be shown again; if it is lost, delete the auth user in the Supabase
 * dashboard and run this again.
 *
 * Usage:
 *   NEXT_PUBLIC_SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... \
 *   SUPABASE_DB_URL='postgres://postgres:...@...pooler.supabase.com:5432/postgres' \
 *     node scripts/bootstrap-admin.mjs "0772123456" "Jane Doe" [RMX-STF-0001]
 */
import pg from 'pg';
import { createClient } from '@supabase/supabase-js';

const [phone, fullName, staffId] = process.argv.slice(2);
const dbUrl = process.env.SUPABASE_DB_URL ?? process.env.DATABASE_URL;
const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!phone || !fullName) {
  console.error('Usage: node scripts/bootstrap-admin.mjs "<phone>" "<full name>" [staffId]');
  process.exit(1);
}
if (!dbUrl) {
  console.error('Set SUPABASE_DB_URL (Supabase → Project Settings → Database → Connection string).');
  process.exit(1);
}

const hosted = Boolean(url && serviceKey);
if (!hosted) {
  console.error(
    'Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.\n' +
    'Without them there is no credential store to create the sign-in identity in.',
  );
  process.exit(1);
}

const client = new pg.Client({
  connectionString: dbUrl,
  ssl: /supabase\.(co|com)/.test(dbUrl) ? { rejectUnauthorized: false } : undefined,
});
await client.connect();

let identityId = null;
const admin = createClient(url, serviceKey, {
  auth: { persistSession: false, autoRefreshToken: false },
});

try {
  // Fail before creating anything if this project already has an administrator.
  const { rows: existing } = await client.query(
    `select count(*)::int as n from public.users where role = 'admin'`,
  );
  if (existing[0].n > 0) {
    console.error(
      '\n  This project already has an administrator.\n' +
      '  Create further accounts from User management inside the application.\n',
    );
    process.exit(1);
  }

  // The identity and the first password, generated by the database so that
  // nobody — including whoever runs this — chooses either.
  const { rows: credentials } = await client.query(
    `select identity, password from app.new_user_credentials()`,
  );
  const { identity, password } = credentials[0];

  const { data, error } = await admin.auth.admin.createUser({
    email: identity,
    password,
    email_confirm: true,
  });
  if (error || !data.user) throw new Error(error?.message ?? 'Could not create the credential.');
  identityId = data.user.id;

  const { rows } = await client.query(
    `select app.bootstrap_first_admin($1, $2, $3, $4) as id`,
    [identityId, phone, fullName, staffId ?? null],
  );

  const { rows: created } = await client.query(
    `select phone_number, full_name, role, must_change_password from public.users where id = $1`,
    [rows[0].id],
  );

  console.log(`
  The first administrator exists.

    Name      ${created[0].full_name}
    Sign in   ${created[0].phone_number}
    Password  ${password}
    Role      ${created[0].role}

  The password is shown once and is not stored anywhere it can be read again.
  Give it to them in person. They will be asked to change it as they sign in${
    created[0].must_change_password ? '' : ' (NOT ENFORCED — this is a bug, report it)'
  }.
`);
} catch (e) {
  // A profile that was never written must not leave a credential behind that
  // nothing points at — that orphan would be a password into nothing.
  if (identityId) {
    await admin.auth.admin.deleteUser(identityId).catch(() => {});
    console.error('  The credential was removed again; nothing was left behind.');
  }
  console.error(`\n  ${(e.message ?? String(e)).replace(/^error:\s*/i, '')}\n`);
  process.exitCode = 1;
} finally {
  await client.end();
}
